dummy-key: 'dummy-value'
dummy-array: [43243,2432,4324,445667]
three: 3
two: 2
acme:
  class: Matecat\SimpleDIC\Dummy\Acme
acme-calculator:
  class: Matecat\SimpleDIC\Dummy\AcmeCalculator
  arguments: ['@three', '@two']
  method: init
  method_arguments: ['@three', '@two']
acme-parser:
  class: Matecat\SimpleDIC\Dummy\AcmeParser
  arguments: ['string']
acme-repo:
  class: Matecat\SimpleDIC\Dummy\AcmeRepo
  arguments: ['@acme']