acme-calculator:
  class: Matecat\SimpleDIC\Dummy\AcmeCalculator
  method: init
acme-repo:
  class: Matecat\SimpleDIC\Dummy\AcmeRepo
  arguments: ['@acme']
not-existing:
  class: Matecat\SimpleDIC\Dummy\NotExistintClass